version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/wordpress"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/nightscout"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/php-8.0"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  
  - package-ecosystem: "docker"
    directory: "/php-8.1"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  
  - package-ecosystem: "docker"
    directory: "/php-8.2"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
                          