version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/wordpress"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/nightscout"
    schedule:
      interval: "daily"
  
