name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the wordpress Docker image
      run: docker build . --file wordpress/Dockerfile --tag wordpress-niepi:$(date +%s)
    - name: Build the nightscout Docker image
      run: docker build . --file nightscout/Dockerfile --tag nightscout-niepi:$(date +%s)
